### ISSUE TITLE
Add feature to modify column width for table in Recipe Setup Window

### ISSUE THREAD

**Issue by ruizhi-wang** [ruizhi-wang/Perlis_v0#12]

**Comment by lukasvasadi** [comment]
By not formatting the column width, the QTableView default settings allow the user to modify the width by dragging the boundary line. However, this causes the initial auto-generated table to be compressed to the lefthand side of the window, instead of filling the available space. As a compromise, I set a fixed width for the columns that is much greater for the step description.
